// ─── Mock Users / Profiles ───────────────────────────────────────────────
export const MOCK_PROFILES = [
  {
    id: 'mock-uuid-1234-5678',
    full_name: 'Rahul Sharma',
    email: 'rahul.sharma@gmail.com',
    phone: '+91 98765 43210',
    role: 'admin',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'user-uuid-aaaa-bbbb',
    full_name: 'Priya Mehta',
    email: 'priya.mehta@example.com',
    phone: '+91 91234 56789',
    role: 'customer',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'user-uuid-cccc-dddd',
    full_name: 'Arjun Nair',
    email: 'arjun.nair@example.com',
    phone: '+91 87654 32109',
    role: 'customer',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'user-uuid-eeee-ffff',
    full_name: 'Sneha Patel',
    email: 'sneha.patel@example.com',
    phone: '+91 76543 21098',
    role: 'customer',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
]

// ─── Mock Orders ─────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  {
    id: 'ord-0001-aaaa-bbbb-cccc-ddddeeee0001',
    user_id: 'user-uuid-aaaa-bbbb',
    status: 'delivered',
    payment_status: 'paid',
    subtotal: 1999,
    delivery_fee: 0,
    total: 1999,
    address: { name: 'Priya Mehta', phone: '+91 91234 56789', line1: '12 MG Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560001' },
    plan_id: 'plan-2',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    profiles: { full_name: 'Priya Mehta' },
    order_items: [
      { id: 'oi-001', product_name: 'Family Dabba Subscription', product_image: null, quantity: 1, unit_price: 1999, total_price: 1999 },
    ],
    order_tracking: [
      { status: 'confirmed', note: 'Order received', created_at: new Date(Date.now() - 8 * 86400000).toISOString() },
      { status: 'processing', note: 'Fruits being packed', created_at: new Date(Date.now() - 7 * 86400000).toISOString() },
      { status: 'shipped', note: 'Out for delivery', created_at: new Date(Date.now() - 6 * 86400000).toISOString() },
      { status: 'delivered', note: 'Delivered successfully', created_at: new Date(Date.now() - 5 * 86400000).toISOString() },
    ],
  },
  {
    id: 'ord-0002-aaaa-bbbb-cccc-ddddeeee0002',
    user_id: 'user-uuid-cccc-dddd',
    status: 'processing',
    payment_status: 'paid',
    subtotal: 848,
    delivery_fee: 0,
    total: 848,
    address: { name: 'Arjun Nair', phone: '+91 87654 32109', line1: '45 Juhu Beach Rd', city: 'Mumbai', state: 'Maharashtra', pincode: '400049' },
    plan_id: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    profiles: { full_name: 'Arjun Nair' },
    order_items: [
      { id: 'oi-002', product_name: 'Alphonso Mango', product_image: '/images/fruit-mango.png', quantity: 1, unit_price: 599, total_price: 599 },
      { id: 'oi-003', product_name: 'Fresh Strawberries', product_image: '/images/fruit-berries.png', quantity: 1, unit_price: 249, total_price: 249 },
    ],
    order_tracking: [
      { status: 'confirmed', note: 'Order confirmed', created_at: new Date(Date.now() - 2 * 86400000).toISOString() },
      { status: 'processing', note: 'Packing in progress', created_at: new Date(Date.now() - 1 * 86400000).toISOString() },
    ],
  },
  {
    id: 'ord-0003-aaaa-bbbb-cccc-ddddeeee0003',
    user_id: 'user-uuid-eeee-ffff',
    status: 'confirmed',
    payment_status: 'paid',
    subtotal: 2999,
    delivery_fee: 0,
    total: 2999,
    address: { name: 'Sneha Patel', phone: '+91 76543 21098', line1: '7 Ring Road', city: 'Ahmedabad', state: 'Gujarat', pincode: '380001' },
    plan_id: 'plan-3',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    profiles: { full_name: 'Sneha Patel' },
    order_items: [
      { id: 'oi-004', product_name: 'Premium Dabba Subscription', product_image: null, quantity: 1, unit_price: 2999, total_price: 2999 },
    ],
    order_tracking: [
      { status: 'confirmed', note: 'Order confirmed', created_at: new Date(Date.now() - 1 * 86400000).toISOString() },
    ],
  },
  {
    id: 'ord-0004-aaaa-bbbb-cccc-ddddeeee0004',
    user_id: 'mock-uuid-1234-5678',
    status: 'pending',
    payment_status: 'paid',
    subtotal: 599,
    delivery_fee: 49,
    total: 648,
    address: { name: 'Rahul Sharma', phone: '+91 98765 43210', line1: '22 Hill View', city: 'Pune', state: 'Maharashtra', pincode: '411001' },
    plan_id: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    profiles: { full_name: 'Rahul Sharma' },
    order_items: [
      { id: 'oi-005', product_name: 'Alphonso Mango', product_image: '/images/fruit-mango.png', quantity: 1, unit_price: 599, total_price: 599 },
    ],
    order_tracking: [],
  },
]

export const MOCK_CATEGORIES = [
  { id: 'cat-1', name: 'Seasonal Fruits', slug: 'seasonal', image_url: null },
  { id: 'cat-2', name: 'Exotic Fruits', slug: 'exotic', image_url: null },
  { id: 'cat-3', name: 'High Protein Fruits', slug: 'high-protein', image_url: null },
  { id: 'cat-4', name: 'Weight Loss Fruits', slug: 'weight-loss', image_url: null },
  { id: 'cat-5', name: 'Immunity Boosting Fruits', slug: 'immunity', image_url: null },
  { id: 'cat-6', name: 'Bowls', slug: 'bowls', image_url: null },
]

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Alphonso Mango',
    slug: 'alphonso-mango',
    description: 'The king of mangoes. Rich, creamy, and aromatic. Sourced from Ratnagiri, Maharashtra.',
    price: 599,
    unit: '1 kg (6-8 pieces)',
    category_id: 'cat-1',
    in_stock: true,
    is_featured: true,
    image_url: '/images/fruit-mango.png',
    nutritional_info: { calories: '99 kcal', vitamin_c: '36mg', fiber: '1.8g' },
    categories: { name: 'Seasonal Fruits', slug: 'seasonal' }
  },
  {
    id: 'prod-2',
    name: 'Fresh Strawberries',
    slug: 'fresh-strawberries',
    description: 'Juicy, sweet strawberries from Mahabaleshwar. Perfect for weight loss.',
    price: 249,
    unit: '500 g punnet',
    category_id: 'cat-4',
    in_stock: true,
    is_featured: true,
    image_url: '/images/fruit-berries.png',
    nutritional_info: { calories: '32 kcal', vitamin_c: '58mg', fiber: '2g' },
    categories: { name: 'Weight Loss Fruits', slug: 'weight-loss' }
  },
  {
    id: 'prod-3',
    name: 'Seedless Green Grapes',
    slug: 'seedless-green-grapes',
    description: 'Crisp and refreshing seedless green grapes. Great for snacking.',
    price: 199,
    unit: '500 g',
    category_id: 'cat-1',
    in_stock: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1423347834838-5162bb452ca4?w=400',
    nutritional_info: { calories: '69 kcal', potassium: '191mg', fiber: '0.9g' },
    categories: { name: 'Seasonal Fruits', slug: 'seasonal' }
  },
  {
    id: 'prod-4',
    name: 'Kiwi Fruit',
    slug: 'kiwi-fruit',
    description: 'Tangy and vitamin-packed New Zealand kiwis. High in Vitamin C and antioxidants.',
    price: 349,
    unit: '6 pieces',
    category_id: 'cat-2',
    in_stock: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1616684000067-36952fde56ec?w=400',
    nutritional_info: { calories: '61 kcal', vitamin_c: '92mg', fiber: '3g' },
    categories: { name: 'Exotic Fruits', slug: 'exotic' }
  },
  {
    id: 'prod-5',
    name: 'Fresh Guava',
    slug: 'fresh-guava',
    description: 'Crisp, pink-fleshed guava. Extremely rich in fiber and proteins.',
    price: 149,
    unit: '1 kg',
    category_id: 'cat-3',
    in_stock: true,
    is_featured: false,
    image_url: '/images/fruit-citrus.png',
    nutritional_info: { calories: '68 kcal', protein: '2.6g', fiber: '5.4g' },
    categories: { name: 'High Protein Fruits', slug: 'high-protein' }
  },
  {
    id: 'prod-6',
    name: 'Dragon Fruit',
    slug: 'dragon-fruit',
    description: 'Exotic pink dragon fruit with white flesh. Mild flavor, stunning appearance.',
    price: 299,
    unit: '1 piece (~400g)',
    category_id: 'cat-2',
    in_stock: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400',
    nutritional_info: { calories: '60 kcal', iron: '0.74mg', fiber: '3g' },
    categories: { name: 'Exotic Fruits', slug: 'exotic' }
  },
  {
    id: 'prod-7',
    name: 'Navel Orange',
    slug: 'navel-orange',
    description: 'Sweet and juicy navel oranges. Excellent source of Vitamin C.',
    price: 129,
    unit: '1 kg (4-5 pieces)',
    category_id: 'cat-5',
    in_stock: true,
    is_featured: true,
    image_url: '/images/fruit-citrus.png',
    nutritional_info: { calories: '47 kcal', vitamin_c: '53mg', fiber: '2.4g' },
    categories: { name: 'Immunity Boosting Fruits', slug: 'immunity' }
  },
  {
    id: 'prod-8',
    name: 'Chikoo (Sapota)',
    slug: 'chikoo-sapota',
    description: 'Sweet, brown sapota with caramel-like taste. A classic Indian fruit.',
    price: 99,
    unit: '500 g (6-8 pieces)',
    category_id: 'cat-1',
    in_stock: true,
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=400',
    nutritional_info: { calories: '83 kcal', iron: '0.8mg', fiber: '5.3g' },
    categories: { name: 'Seasonal Fruits', slug: 'seasonal' }
  },
  {
    id: 'prod-9',
    name: 'Blueberries',
    slug: 'blueberries',
    description: 'Premium imported blueberries. Packed with antioxidants and brain-boosting benefits.',
    price: 499,
    unit: '125 g punnet',
    category_id: 'cat-2',
    in_stock: true,
    is_featured: true,
    image_url: '/images/fruit-berries.png',
    nutritional_info: { calories: '57 kcal', vitamin_c: '9.7mg', fiber: '2.4g' },
    categories: { name: 'Exotic Fruits', slug: 'exotic' }
  },
  {
    id: 'prod-10',
    name: 'Pineapple',
    slug: 'pineapple',
    description: 'Sweet and tangy fresh pineapple. Great for digestion and immunity boosting.',
    price: 79,
    unit: '1 piece (~1.2kg)',
    category_id: 'cat-5',
    in_stock: true,
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1490885578174-acda8905c2c6?w=400',
    nutritional_info: { calories: '50 kcal', vitamin_c: '47mg', fiber: '1.4g' },
    categories: { name: 'Immunity Boosting Fruits', slug: 'immunity' }
  },
  {
    id: 'prod-11',
    name: 'Avocado',
    slug: 'avocado',
    description: 'Creamy and buttery Hass avocados. Extremely rich in healthy fats and proteins.',
    price: 449,
    unit: '2 pieces',
    category_id: 'cat-3',
    in_stock: true,
    is_featured: true,
    image_url: 'https://images.unsplash.com/photo-1601039641847-7857b994d704?w=400',
    nutritional_info: { calories: '160 kcal', protein: '2g', fiber: '7g' },
    categories: { name: 'High Protein Fruits', slug: 'high-protein' }
  },
  {
    id: 'prod-12',
    name: 'Custard Apple',
    slug: 'custard-apple',
    description: 'Creamy and sweet sitaphal. High in calories and healthy fibers.',
    price: 199,
    unit: '2 pieces',
    category_id: 'cat-1',
    in_stock: true,
    is_featured: false,
    image_url: 'https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=400',
    nutritional_info: { calories: '101 kcal', vitamin_c: '19mg', fiber: '4.4g' },
    categories: { name: 'Seasonal Fruits', slug: 'seasonal' }
  },
  {
    id: 'prod-13',
    name: 'Mixed Fruit Bowl',
    slug: 'mixed-fruit-bowl',
    description: 'A refreshing mix of seasonal favorites like apples, bananas, grapes, and papaya.',
    price: 149,
    unit: '1 bowl (~400g)',
    category_id: 'cat-6',
    in_stock: true,
    is_featured: true,
    image_url: '/images/item-fruit-bowl.png',
    nutritional_info: { calories: '140 kcal', fiber: '4.2g', vitamins: 'A, C' },
    categories: { name: 'Bowls', slug: 'bowls' }
  },
  {
    id: 'prod-14',
    name: 'Protein Fruit Bowl',
    slug: 'protein-fruit-bowl',
    description: 'Power-packed with bananas, pomegranate, kiwi, almonds, and pumpkin seeds.',
    price: 199,
    unit: '1 bowl (~400g)',
    category_id: 'cat-6',
    in_stock: true,
    is_featured: true,
    image_url: '/images/item-melon-bowl.png',
    nutritional_info: { calories: '220 kcal', protein: '8g', fiber: '5.5g' },
    categories: { name: 'Bowls', slug: 'bowls' }
  },
  {
    id: 'prod-15',
    name: 'Kids Fruit Bowl',
    slug: 'kids-fruit-bowl',
    description: 'Fun, bite-sized sweet fruits like strawberries, grapes, mangoes, and apples.',
    price: 149,
    unit: '1 bowl (~350g)',
    category_id: 'cat-6',
    in_stock: true,
    is_featured: true,
    image_url: '/images/item-berry-smoothie.png',
    nutritional_info: { calories: '130 kcal', vitamin_c: '45mg', fiber: '3g' },
    categories: { name: 'Bowls', slug: 'bowls' }
  },
  {
    id: 'prod-16',
    name: 'Detox Fruit Bowl',
    slug: 'detox-fruit-bowl',
    description: 'Antioxidant-rich berries, citrus segments, kiwi, and mint leaves.',
    price: 179,
    unit: '1 bowl (~350g)',
    category_id: 'cat-6',
    in_stock: true,
    is_featured: true,
    image_url: '/images/item-green-juice.png',
    nutritional_info: { calories: '110 kcal', fiber: '4.8g', vitamins: 'A, C, K' },
    categories: { name: 'Bowls', slug: 'bowls' }
  },
  {
    id: 'prod-17',
    name: 'Office Fruit Bowl',
    slug: 'office-fruit-bowl',
    description: 'Energy-boosting office desk companion with apples, pears, seedless grapes, and oranges.',
    price: 249,
    unit: '1 bowl (~450g)',
    category_id: 'cat-6',
    in_stock: true,
    is_featured: true,
    image_url: '/images/item-orange-juice.png',
    nutritional_info: { calories: '160 kcal', potassium: '380mg', fiber: '5g' },
    categories: { name: 'Bowls', slug: 'bowls' }
  },
]

export const MOCK_PLANS = [
  {
    id: 'plan-1',
    name: 'Basic Pack',
    slug: 'basic-pack',
    description: 'Weight: 300-350 gms. Minimum 4-5 fruits per day.',
    price: 3060.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Weight: 300-350 gms', 'Minimum 4-5 fruits', 'Excludes Sundays (26 deliveries)', 'Free doorstep delivery', 'Sourced fresh daily'],
  },
  {
    id: 'plan-2',
    name: 'Mini Pack',
    slug: 'mini-pack',
    description: 'Weight: 400-450 gms. Minimum 4-5 fruits per day.',
    price: 3580.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Weight: 400-450 gms', 'Minimum 4-5 fruits', 'Excludes Sundays (26 deliveries)', 'Free doorstep delivery', 'Sourced fresh daily'],
  },
  {
    id: 'plan-3',
    name: 'Medium Pack',
    slug: 'medium-pack',
    description: 'Weight: 500-550 gms. Includes 4-5 fruits + legumes.',
    price: 4099.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: true,
    features: ['Weight: 500-550 gms', '4-5 fruits + healthy legumes', 'Excludes Sundays (26 deliveries)', 'Free doorstep delivery', 'High protein & nutrients'],
  },
  {
    id: 'plan-4',
    name: 'Premium Pack',
    slug: 'premium-pack',
    description: 'Weight: 700-750 gms. Includes 6-7 fruits + legumes + nuts.',
    price: 4620.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Weight: 700-750 gms', '6-7 fruits + legumes + premium nuts', 'Excludes Sundays (26 deliveries)', 'Free priority delivery', 'Complete daily nutrition'],
  },
  {
    id: 'plan-5',
    name: 'Gym High Protein Pack',
    slug: 'gym-protein-pack',
    description: 'Daily high-protein salad bowl with premium healthy add-ins.',
    price: 4499.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Daily High-protein salad bowl', 'Includes pomegranate, kiwi, paneer/tofu', 'Excludes Sundays (26 deliveries)', 'Free doorstep delivery', 'High protein & fiber-rich'],
  },
  {
    id: 'plan-6',
    name: 'Corn Chaat & Salad Pack',
    slug: 'corn-chaat-pack',
    description: 'Daily fresh tangy corn chaat and green salad mix.',
    price: 3999.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Daily fresh corn chaat', 'Tangy & fiber-rich mix', 'Excludes Sundays (26 deliveries)', 'Free doorstep delivery', 'Perfect afternoon snack'],
  },
  {
    id: 'plan-7',
    name: 'Custom Dabba Pack',
    slug: 'custom-pack',
    description: 'Fully customized daily health pack based on your choices.',
    price: 3000.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Choose your own ingredients', 'Base price of ₹3,000', 'Custom categories and exclusions', 'Flexible portion pack size'],
  },

  // ── Fruit Box Trials ──────────────────────────────────────────────────
  {
    id: 'plan-t1',
    name: 'Fruit Box — 3 Day Trial',
    slug: 'fruit-trial-3d',
    description: 'Try our daily seasonal fruit box for 3 days. No commitment.',
    price: 349.00,
    duration_days: 3,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['5+ Fresh Fruits per day', '3 daily deliveries', 'Seasonal & exotic mix', 'Free doorstep delivery'],
  },
  {
    id: 'plan-t2',
    name: 'Fruit Box — 6 Day Trial',
    slug: 'fruit-trial-6d',
    description: 'Try our daily seasonal fruit box for 6 days. Experience the full week.',
    price: 699.00,
    duration_days: 6,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['5+ Fresh Fruits per day', '6 daily deliveries', 'No repeat varieties', 'Free doorstep delivery'],
  },

  // ── Oat Meal Trials ───────────────────────────────────────────────────
  {
    id: 'plan-t3',
    name: 'Oat Meal — 3 Day Trial',
    slug: 'oat-trial-3d',
    description: 'Try our freshly prepared oat meals for 3 days.',
    price: 299.00,
    duration_days: 3,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Freshly prepared daily', 'High fiber & protein', '3 daily deliveries', 'Warm or cold option'],
  },
  {
    id: 'plan-t4',
    name: 'Oat Meal — 6 Day Trial',
    slug: 'oat-trial-6d',
    description: 'Try our freshly prepared oat meals for 6 days.',
    price: 599.00,
    duration_days: 6,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Freshly prepared daily', 'High fiber & protein', '6 daily deliveries', 'No preservatives'],
  },
  {
    id: 'plan-t5',
    name: 'Oat Meal — Monthly',
    slug: 'oat-monthly',
    description: 'Full month of freshly prepared oat meals. 26 daily deliveries.',
    price: 3699.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['Freshly prepared daily', '26 deliveries per month', 'High fiber & protein', 'No preservatives'],
  },

  // ── Salad Bowl Trials ─────────────────────────────────────────────────
  {
    id: 'plan-t6',
    name: 'Salad Bowl — 3 Day Trial',
    slug: 'salad-trial-3d',
    description: 'Try our fresh salad bowls for 3 days. Healthy & filling.',
    price: 349.00,
    duration_days: 3,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['1 fresh salad per day', 'Hygienically prepared', '3 daily deliveries', 'Timely delivery'],
  },
  {
    id: 'plan-t7',
    name: 'Salad Bowl — 6 Day Trial',
    slug: 'salad-trial-6d',
    description: 'Try our fresh salad bowls for 6 days.',
    price: 699.00,
    duration_days: 6,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['1 fresh salad per day', 'No repeats in 6 days', '6 daily deliveries', 'Timely delivery'],
  },

  // ── Juice Trials ──────────────────────────────────────────────────────
  {
    id: 'plan-t8',
    name: 'Juice — 3 Day Trial',
    slug: 'juice-trial-3d',
    description: 'Try our cold-pressed fresh juice subscription for 3 days.',
    price: 349.00,
    duration_days: 3,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['100% fresh cold-pressed', 'No sugar added', '3 daily deliveries', 'Sealed & chilled delivery'],
  },
  {
    id: 'plan-t9',
    name: 'Juice — 6 Day Trial',
    slug: 'juice-trial-6d',
    description: 'Try our cold-pressed fresh juice subscription for 6 days.',
    price: 699.00,
    duration_days: 6,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['100% fresh cold-pressed', 'No preservatives', '6 daily deliveries', 'Sealed & chilled delivery'],
  },
  {
    id: 'plan-t10',
    name: 'Juice — Monthly',
    slug: 'juice-monthly',
    description: 'Full month of cold-pressed fresh juices. 26 daily deliveries.',
    price: 3999.00,
    duration_days: 30,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['100% fresh cold-pressed', 'No preservatives', '26 deliveries per month', 'Sealed & chilled delivery'],
  },

  // ── Protein Bowl Trials ───────────────────────────────────────────────
  {
    id: 'plan-t11',
    name: 'Protein Bowl — 3 Day Trial',
    slug: 'protein-trial-3d',
    description: 'Try our high-protein gym bowls for 3 days.',
    price: 399.00,
    duration_days: 3,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['25g+ protein per bowl', 'Post-workout optimized', '3 daily deliveries', 'Macro-balanced meals'],
  },
  {
    id: 'plan-t12',
    name: 'Protein Bowl — 6 Day Trial',
    slug: 'protein-trial-6d',
    description: 'Try our high-protein gym bowls for 6 days.',
    price: 799.00,
    duration_days: 6,
    discount_pct: 0,
    delivery_frequency: 'daily',
    is_popular: false,
    features: ['25g+ protein per bowl', 'Post-workout optimized', '6 daily deliveries', 'Fresh ingredients daily'],
  },
]
